import { NEWTONS_PER_POUND_FORCE } from "../force/constants.js";

const METERS_PER_FOOT = 0.3048;
const METERS_PER_INCH = 0.0254;

export const PASCALS_PER_HECTOPASCAL = 100;

/** PSI → Pa */
export const PASCALS_PER_PSI = NEWTONS_PER_POUND_FORCE / (METERS_PER_INCH * METERS_PER_INCH);

/** PSF → Pa */
export const PASCALS_PER_PSF = NEWTONS_PER_POUND_FORCE / (METERS_PER_FOOT * METERS_PER_FOOT);
