import { KILOGRAMS_PER_SLUG } from "../mass/constants.js";

const METERS_PER_FOOT = 0.3048;
const SQUARE_METERS_PER_SQUARE_FOOT = METERS_PER_FOOT * METERS_PER_FOOT;

/** slug·ft² → kg·m² */
export const KILOGRAM_METER_SQUARED_PER_SLUG_FOOT_SQUARED =
  KILOGRAMS_PER_SLUG * SQUARE_METERS_PER_SQUARE_FOOT;
